sudo: required
dist: trusty

language: python
python:
    - "3.4"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y gettext mplayer libgettextpo-dev python3-pyqt5 pyqt5-dev-tools intltool autopoint python3-pytest
    - pip install chardet
 
before_script:
    - ./autogen.sh && ./configure

script: 
    - make
    - make test
    - make dist-all
