language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y gettext libgettextpo-dev mplayer python3-pyqt4 pyqt4-dev-tools intltool autopoint
    - pip install chardet
 
before_script:
    - ./autogen.sh && ./configure

script: 
    - make
    - make test
    - make dist-all
