sudo: required
dist: trusty
language: generic

matrix:
    include:
        - os: linux
          language: python
          env: TESTENV=py34 POSARGS="-n 8"
          python: 3.4

        - os: linux
          language: python
          env: TESTENV=py35 POSARGS="-n 8"
          python: 3.5

        - os: linux
          language: python
          env: TESTENV=py36 POSARGS="-n 8"
          python: 3.6

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y mplayer
    - pip install tox

cache:
  directories:
    - $HOME/.cache/pip
 
script: 
    - tox -e $TESTENV -- $POSARGS
