sudo: required
dist: trusty
language: generic

matrix:
    include:
        - os: linux
          language: python
          env: TESTENV=py34 PATH=/usr/bin:$PATH
          python: 3.4

        - os: linux
          language: python
          env: TESTENV=py35
          python: 3.5

        - os: linux
          language: python
          env: TESTENV=py36
          python: 3.6

before_install:
    - sudo apt-get update -qq

install:
    - travis_install $TESTENV

cache:
  directories:
    - $HOME/.cache/pip

script:
    - travis_run
