language: python
python:
    - "3.2_with_system_site_packages"

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y gettext libgettextpo-dev python3-pyqt4 pyqt4-dev-tools intltool autopoint
    - pip install chardet
 
before_script:
    - ./autogen.sh && ./configure

script: 
    - make
    - make test
    - make dist-all
