language: python
python:
    - "3.2_with_system_site_packages"

before_install:
    - sudo apt-get update -qq
    - sudo ln -s "`which nosetests`" "`which nosetests`3" # yea...

install:
    - sudo apt-get install -y gettext mplayer libgettextpo-dev python3-pyqt5 pyqt5-dev-tools intltool autopoint
    - pip install chardet
 
before_script:
    - ./autogen.sh && ./configure

script: 
    - make
    - make test
    - make dist-all
