[[installation]]
== Installation
:1: http://nedbatchelder.com/code/coverage/
:2: https://pypi.python.org/pypi/coverage
:3: https://nose.readthedocs.org/en/latest/plugins/cover.html

NOTE: Since version 1.0.0 Subconvert installation procedure changes. Previous
`install.sh` script has been replaced with `autotools`. Currently Subconvert
uses standard `autotools` build and installation procedure.

=== Preparing a build system

NOTE: you can skip this step if you downloaded a release package (i.e.
      `configure` script already exists).*

In Subconvert directory you should find `autogen.sh` script which prepares a
build system. To run it you need `autotools` (specifically `autoconf` and
`automake`) and `intltool` installed on your system. When it's done, `autogen`
will display *Quick Install Reference*.

----
$ ./autogen.sh
----

=== Configuring installation

When build system is ready, it is time to configure your installatio. Typically
it's done by calling a `configure` script:

----
$ ./configure
----

Configure is a script generated by `autoconf`. It has a lot of options (you can
learn about all of them via `$ configure --help`) but probably the most
important one is `--prefix` changes your installation path. Every time you
install (or reinstall) Subconvert, it will be installed into the following
directories:

----
${prefix}/bin - Subconvert executable (usually just a symlink)
${prefix}/share/subconvert - Subconvert code and data (like images)
${prefix}/share/applications - .desktop file
${prefix}/share/locale - message catalogs (translations)
----

If you don't specify a `--prefix` option, default prefix will be used, i.e.
`/usr`. If you don't have root privileges on a system that you'd like to install
Subconvert on, you can change prefix e.g. to `${HOME}/.local`. If you follow
that advice, just remember that `${HOME}/.local/bin` usually isn't added to
`$PATH`. You might consider adding it to $PATH or creating a symlink to
`${HOME}/.local/bin/subconvert`.

Example:

----
$ ./configure --prefix=${HOME}/.loocal
----

=== Building and installing

Building and installing Subconvert is pretty straightforward now (at least if
you have all dependencies met).

To build and generate all files needed by Subconvert, run:

----
$ make
----

And to install Subconvert:

----
$ make install
----

You cannot install Subconvert twice (e.g. when updating). Before a new
installation, remove the old one (don't worry, you won't lose your settings).
For a convenience you can also use `reinstall` target which will first remove
any previous Subconvert installation from a configured `${prefix}` and then
install a new one. In fact, you can use it all the time, even if you haven't
installed Subconvert previously.

----
$ make reinstall
----

==== Building documentation

Subconvert's documentation is stored in `docs` directory. To build it:

----
$ cd docs
$ make
----

This should create `docs/build` directory in which documentation in several
formats will be generated. Choose the one you like the most.

=== Removing Subconvert

To remove Subconvert automatically you must configure it the same way as you did
above. Remember to specify correct `${prefix}` path or else build system won't
be able to remove Subconvert correctly. If you don't know or don't remember
where Subconvert is installed on your system but it is visible in `$PATH`, you
can examine the output of `$ which subconvert`.

When you're done with `configure` script, removing Subconvert is simple:

----
$ make uninstall
----

=== Dependencies

==== Runtime dependencies

* `Python 3.2+`
* `python3-pyqt5`
* `python3-chardet`
* `MPlayer`
* `gettext`

==== Build dependencies

These dependencies are only valid if you do not have pre-generated `configure`
script in your Subconvert download.

* `autotools` (`autoconf` + `automake`)
* `intltool`
* `pyrcc5` (comes with `pyqt5-dev-tools`)

==== Documentation

* `asciidoctor` (`asciidoc` works too)

==== Running tests

* `python3-nose`
* `python3-coverage` (see: link:{1}[homepage] and link:{2}[PyPi] and
  link:{3}[nose plugin page])

// vim: set tw=80 colorcolumn=81 ft=asciidoc :
