#!/bin/sh

die() {
    printf "%s\n" "$1" >&2
    exit 1
}

case $TESTENV in
    py3*)
        tox -e $TESTENV -- -n 4
        ;;
    *)
        die "Icorrect (unsupported) TESTENV: $TESTENV"
        ;;
esac
