#!/bin/sh

set -e

DIR="$( dirname "$(readlink -f "$0")")"

die() {
    printf "%s\n" "$1" >&2
    exit 1
}

case $TESTENV in
    py3*)
        tox -e $TESTENV -- -n 4
        ;;
    sdist|bdist|bdist_wheel)
        $DIR/dist_test "$TESTENV"
        ;;
    *)
        die "Icorrect (unsupported) TESTENV: $TESTENV"
        ;;
esac
